---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/simonxox/k8s-ingress.git
    targetRevision: HEAD
    path: .        # 👈 relative
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy: { automated: { prune: true, selfHeal: true } }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/simonxox/k8s-ingress.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy: { automated: { prune: true, selfHeal: true } }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/simonxox/k8s-ingress.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy: { automated: { prune: true, selfHeal: true } }

